# SPDX-FileCopyrightText: 2023 Dinesh Ravi
#
# SPDX-License-Identifier: GPL-3.0-only

apihost: https://blackduck.ebgroup.elektrobit.com/api/
token: "token Mzg4NDk5MjAtZTA2ZC00M2FlLTkzYWUtNzdkYWE5MDExZmQ1OjNlZGU4NzI3LWMxNDYtNGQzMy1iMThmLTdhZGI0YTg5YTNmMA=="